import type { LlmCallResult, LlmRequest } from '../executor/llm.js'
import type { LogEvent, RunMeta } from '../executor/types.js'
import { deriveInterruptHistory, parseLogEventLine } from './render.js'

// One-line run summaries for the history list and the watch top bar, generated by the same model the guild runs on. Two summaries are produced per run: a start summary from the task alone, and a completion summary that replaces it, derived from the task, the interrupt history, and the final result — the completion pass states what the run actually did, which the task text alone often does not ("the first line of the prompt" is not a reliable stand-in). Summaries are service-level bookkeeping, not agent work: they are not logged as run events, and a failure at either point leaves the UI on the task-text fallback — a run never fails over a label.

export type CallLlm = (request: LlmRequest) => Promise<LlmCallResult>
export type ReadRunLogText = (runId: string) => string
export type WriteRunSummaryText = (runId: string, summary: string) => void

export interface TaskSummarizerDependencies {
	callLlm: CallLlm
	readRunLogText: ReadRunLogText
	writeRunSummaryText: WriteRunSummaryText
}

export interface TaskSummarizer {
	summarizeTaskStart(runId: string, task: string): Promise<void>
	summarizeRunCompletion(meta: RunMeta): Promise<void>
}

const SUMMARY_WORD_BUDGET = 15
const SUMMARY_CHAR_CAP = 140

const START_SYSTEM_PROMPT = `You summarize tasks for a run-history list. Reply with exactly one line of at most ${SUMMARY_WORD_BUDGET} words describing what the user wants, in plain language. No preamble, no quotes, no Markdown.`

const COMPLETION_SYSTEM_PROMPT = `You summarize what an automated run accomplished for a run-history list. Reply with exactly one line of at most ${SUMMARY_WORD_BUDGET} words in past tense, plain language. No preamble, no quotes, no Markdown.`

// Reduces whatever the model returned to a single bounded line: the first non-empty line, stripped of list/heading/quote scaffolding the model tends to add despite instructions, capped at a word boundary so an overrun reads as an intentional ellipsis rather than a mid-word cut. Returns null when nothing usable remains.
function toOneLineSummary(content: string): string | null {
	const firstLine = content.split('\n').map((line) => line.trim()).find((line) => line !== '')
	if (firstLine === undefined) return null
	let text = firstLine
	let previous: string
	do {
		previous = text
		text = text.replace(/^(?:[-*+]\s*|#{1,6}\s*|>\s*|\d+[.)]\s*)/, '')
	} while (text !== previous)
	if (text.length >= 2 && text.startsWith('"') && text.endsWith('"')) text = text.slice(1, -1).trim()
	if (text === '') return null
	if (text.length <= SUMMARY_CHAR_CAP) return text
	const capped = text.slice(0, SUMMARY_CHAR_CAP)
	const lastSpace = capped.lastIndexOf(' ')
	return `${lastSpace > SUMMARY_CHAR_CAP / 2 ? capped.slice(0, lastSpace) : capped}…`
}

// deriveInterruptHistory consumes only interrupt, interrupt_resolved, and plan_modification events, and llm_call events carrying full prompts dominate a long log. Every logged event serializes its type as the JSON substring `"type":"<type>"` (the writer uses plain JSON.stringify and these type values contain no escapable characters), so a line without one of these markers cannot parse into a relevant event and is skipped before JSON parsing. A marker inside a payload string also passes the filter and is discarded downstream — the filter only has to never skip a relevant line, never to match exactly.
const INTERRUPT_EVENT_MARKERS = ['"type":"interrupt', '"type":"plan_modification'] as const

function parseInterruptLogEvents(logText: string): LogEvent[] {
	const events: LogEvent[] = []
	for (const line of logText.split('\n')) {
		if (!INTERRUPT_EVENT_MARKERS.some((marker) => line.includes(marker))) continue
		const event = parseLogEventLine(line)
		if (event !== null) events.push(event)
	}
	return events
}

function completionBriefing(meta: RunMeta, logText: string): string {
	const lines = [`Task: ${meta.task}`]
	for (const entry of deriveInterruptHistory(parseInterruptLogEvents(logText))) {
		if (entry.kind === 'inquiry') {
			lines.push(`The operator asked: ${entry.message}`)
			if (entry.answer !== null) lines.push(`The run answered: ${entry.answer}`)
			continue
		}
		lines.push(`The operator changed the plan: ${entry.message}`)
	}
	if (meta.result !== undefined && meta.result.summary !== '') lines.push(`Outcome (${meta.status}): ${meta.result.summary}`)
	if (meta.error !== undefined && meta.error.message !== '') lines.push(`Error: ${meta.error.message}`)
	return lines.join('\n')
}

async function summarizeAndWrite(dependencies: TaskSummarizerDependencies, runId: string, systemPrompt: string, userText: string): Promise<void> {
	const result = await dependencies.callLlm({ messages: [{ role: 'system', content: systemPrompt }, { role: 'user', content: userText }] })
	if (result.kind !== 'success' || result.content === undefined) return
	const summary = toOneLineSummary(result.content)
	if (summary === null) return
	dependencies.writeRunSummaryText(runId, summary)
}

export function createTaskSummarizer(dependencies: TaskSummarizerDependencies): TaskSummarizer {
	return {
		summarizeTaskStart(runId, task) {
			return summarizeAndWrite(dependencies, runId, START_SYSTEM_PROMPT, task)
		},
		summarizeRunCompletion(meta) {
			return summarizeAndWrite(dependencies, meta.runId, COMPLETION_SYSTEM_PROMPT, completionBriefing(meta, dependencies.readRunLogText(meta.runId)))
		},
	}
}
